version: 2
jobs:
  build:
    docker:
      - image: node:10.15.2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "de:cd:66:57:8d:0d:d5:65:4f:8e:c1:7a:04:d7:d5:ac"
      - run:
          name: Install dependencies
          command: |
            npm config set unsafe-perm true
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@tigercat2000.dev"
            git config user.name "ci-build"
            npm install --dev
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy to gh-pages
          command: gh-pages --dotfiles --dist dist --message "[skip ci] Updates"